services:
  app:
    image: 'snowdreamtech/frps'
    container_name: frps
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    volumes:
      - './frps.toml:/etc/frp/frps.toml'
