version: '3.8'
services:
  app:
    image: 'mongodb/mongodb-community-server'
    container_name: mongodb
    restart: unless-stopped
    network_mode: host
    volumes:
      - '.data:/data/db'
    env_file:
      - .env
    expose:
      - 27017
