services:
  app:
    image: 'snowdreamtech/frpc'
    container_name: frpc
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    network_mode: host
    volumes:
      - './frpc.toml:/etc/frp/frpc.toml'
