version: '3.3'
services:
    portainer:
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '.data:/data'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        ports:
            - '8000:8000'
            - '9000:9000'    
        container_name: portainer
        image: 'portainer/portainer-ce'
  
