version: '3.8'
services:
  app:
    image: 'mysql'
    container_name: mysql
    restart: unless-stopped
    network_mode: host
    volumes:
      - './data:/var/lib/mysql'
    env_file:
      - .env  
